export const UPDATE_TOUR_NAME = 'UPDATE_TOUR_NAME';
export const UPDATE_TOUR_BUILDING_NAME = 'UPDATE_TOUR_BUILDING_NAME';
export const UPDATE_TOUR_DESCRIPTION = 'UPDATE_TOUR_DESCRIPTION';

export const GOTO_NEXT_STAGE = 'GOTO_NEXT_STAGE';
export const UPLOAD_FLOORPLAN = 'UPLOAD_FLOORPLAN';
export const RENAME_FLOORPLAN = 'RENAME_FLOORPLAN';
export const DELETE_FLOORPLAN = 'DELETE_FLOORPLAN';
export const UPLOAD_PANORAMA = 'UPLOAD_PANORAMA';
export const RENAME_PANORAMA = 'RENAME_PANORAMA';
export const DELETE_PANORAMA = 'DELETE_PANORAMA';
export const UPDATE_ASSET_LOAD = 'UPDATE_ASSET_LOAD';

export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';
export const CHANGE_CONTENT = 'CHANGE_CONTENT';
export const SET_CREATE_TOUR = 'SET_CREATE_TOUR';
export const RECEIVE_SELF = 'RECEIVE_SELF';

//TOUR DESIGN
export const FETCH_TOUR = 'FETCH_TOUR';
export const RECEIVE_TOUR = 'RECEIVE_TOUR';
export const UPDATE_PANORAMA_LABEL = 'UPDATE_PANORAMA_LABEL';
export const BEGIN_PANORAMA_DRAG = 'BEGIN_PANORAMA_DRAG';
export const ENABLE_DRAG = 'ENABLE_DRAG';
export const END_PANORAMA_DRAG = 'END_PANORAMA_DRAG';
export const UPDATE_MOUSE = 'UPDATE_MOUSE';
export const MOUSE_OVER_FLOORPLAN = 'MOUSE_OVER_FLOORPLAN';
export const MOUSE_LEAVE_FLOORPLAN = 'MOUSE_LEAVE_FLOORPLAN';
export const UPDATE_PANORAMA_POSITION = 'UPDATE_PANORAMA_POSITION';
export const RECEIVE_PREVIEW_CONTAINER = 'RECEIVE_PREVIEW_CONTAINER';
export const PREVIEW_PANORAMA = 'PREVIEW_PANORAMA';
export const ACTIVATE_TOOL = 'ACTIVATE_TOOL';
export const ADD_EDGE = 'ADD_EDGE';
export const REMOVE_EDGE = 'REMOVE_EDGE';
export const ERASE_PANORAMA = 'ERASE_PANORAMA';
export const UPLOAD_TOUR = 'UPLOAD_TOUR';
export const UPLOAD_REDIRECT = 'UPLOAD_REDIRECT';
export const ADD_FLOOR = 'ADD_FLOOR';
export const SET_FLOORPLAN_ROTATION = 'SET_FLOORPLAN_ROTATION';
export const SAVE_TOUR = 'SAVE_TOUR';
export const SHIFT_FLOOR = 'SHIFT_FLOOR';
export const UPDATE_VIEWBOX = 'UPDATE_VIEWBOX';

export const ACTIVATE_CONFIRMATION = 'ACTIVATE_CONFIRMATION';
export const DEACTIVATE_CONFIRMATION = 'DEACTIVATE_CONFIRMATION';

export const REMOVE_TOUR = "REMOVE_TOUR";